name: Test Jest Preset

on: push

jobs:
  expect-failure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Run test
        run: yarn test
  expect-success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Patch dependency `react-native`
        run: yarn patch-package
      - name: Run test
        run: yarn test
