name: Test Jest Preset

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
      - name: Run test
        run: yarn test
        continue-on-error: true
